# Generated by Django 2.2.19 on 2022-04-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0012_remove_step_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to='database.Language', verbose_name='Язык')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='database.Step', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Статистика по шагу за день',
                'verbose_name_plural': 'Статистика по шагам за день',
                'ordering': ['date', 'step', 'language'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teleram_id', models.CharField(max_length=20, unique=True, verbose_name='Telegram bot id')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('status', models.CharField(choices=[('OK', 'Активный'), ('BL', 'Забанен')], default='OK', max_length=2, verbose_name='Статус')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='database.Country', verbose_name='Страна')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='database.Language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Пользовательница',
                'verbose_name_plural': 'Пользовательницы',
            },
        ),
    ]
