# Generated by Django 2.2.19 on 2022-04-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='teleram_id',
            new_name='telegram_id',
        ),
    ]
