# Generated by Django 2.2.19 on 2022-04-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_remove_step_parent'),
        ('chatbot', '0002_auto_20220426_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='current_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_current_step', to='database.Step', verbose_name='Текущий шаг'),
        ),
        migrations.AddField(
            model_name='client',
            name='previous_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_previous_step', to='database.Step', verbose_name='Предыдущий шаг'),
        ),
    ]
