# Generated by Django 2.2.19 on 2022-04-25 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=20, verbose_name='Название для админки')),
                ('eu', models.BooleanField(verbose_name='Член ЕС')),
                ('active', models.BooleanField(verbose_name='Активна в боте')),
                ('code_iso', models.CharField(max_length=3, verbose_name='Код ISO')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название языка')),
                ('code', models.CharField(max_length=2, verbose_name='Двубуквенный код')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30, verbose_name='Название')),
                ('code', models.CharField(max_length=3, verbose_name='Трёхбуквенный код')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя шага англ')),
                ('button_ukr', models.CharField(max_length=60, verbose_name='Кнопка на украинском')),
                ('button_rus', models.CharField(max_length=60, verbose_name='Кнопка на русском')),
                ('text_ukr', models.TextField(blank=True, null=True, verbose_name='Текст на украинском')),
                ('text_rus', models.TextField(verbose_name='Текст на русском')),
                ('file_ukr', models.FileField(blank=True, upload_to='files/', verbose_name='Файл на украинском')),
                ('file_rus', models.FileField(blank=True, upload_to='files/', verbose_name='Файл на русском')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Когда изменён')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='database.Country', verbose_name='Страна')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='database.Section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='database.Step', verbose_name='Куда')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='database.Step', verbose_name='Откуда')),
            ],
            options={
                'verbose_name': 'Переход',
                'verbose_name_plural': 'Переходы',
            },
        ),
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='database.Country', verbose_name='Страна')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countrynames', to='database.Language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Название страны',
                'verbose_name_plural': 'Названия стран',
            },
        ),
    ]
