# Generated by Django 2.2.19 on 2022-04-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20220425_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-id'], 'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
    ]
