# Generated by Django 2.2.19 on 2022-04-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20220425_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['id'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='countryname',
            options={'ordering': ['country', 'language'], 'verbose_name': 'Название страны', 'verbose_name_plural': 'Названия стран'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['id'], 'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
    ]
