# Generated by Django 2.2.19 on 2022-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20220425_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='admin_name',
        ),
        migrations.AddField(
            model_name='section',
            name='name_rus',
            field=models.CharField(default='def', max_length=30, verbose_name='Название на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='name_ukr',
            field=models.CharField(default='def_u', max_length=30, verbose_name='Название на украинском'),
            preserve_default=False,
        ),
    ]
