# Generated by Django 2.2.19 on 2022-04-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20220425_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['country', 'section', 'name'], 'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('country', 'name')},
        ),
    ]
