# Generated by Django 2.2.19 on 2022-04-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20220425_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transition',
            options={'ordering': ['parent', 'child'], 'verbose_name': 'Переход', 'verbose_name_plural': 'Переходы'},
        ),
    ]
