# Generated by Django 2.2.19 on 2022-04-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20220425_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='parent',
            field=models.ManyToManyField(limit_choices_to={'country': 'self.country'}, related_name='_step_parent_+', to='database.Step'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tparents', to='database.Step', verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tchildren', to='database.Step', verbose_name='Откуда'),
        ),
    ]
