# Generated by Django 2.2.19 on 2022-04-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20220425_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='parent',
            field=models.ManyToManyField(related_name='_step_parent_+', to='database.Step'),
        ),
    ]
