# Generated by Django 2.2.19 on 2022-04-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20220425_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='parent',
        ),
    ]
