# Generated by Django 2.2.19 on 2022-05-07 08:41

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20220429_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='text_rus',
            field=models.TextField(validators=[database.models.validate_no_dbl_quotes], verbose_name='Текст на русском'),
        ),
        migrations.AlterField(
            model_name='step',
            name='text_ukr',
            field=models.TextField(blank=True, null=True, validators=[database.models.validate_no_dbl_quotes], verbose_name='Текст на украинском'),
        ),
    ]
