# Generated by Django 2.2.19 on 2022-05-07 08:45

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20220507_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='button_rus',
            field=models.CharField(max_length=46, validators=[database.models.validate_no_dbl_quotes], verbose_name='Кнопка на русском'),
        ),
        migrations.AlterField(
            model_name='step',
            name='button_ukr',
            field=models.CharField(max_length=46, validators=[database.models.validate_no_dbl_quotes], verbose_name='Кнопка на украинском'),
        ),
    ]
