# Generated by Django 2.2.19 on 2022-05-07 08:52

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20220507_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='button_rus',
            field=models.CharField(help_text='Максимум 46 символов', max_length=46, validators=[database.models.validate_no_dbl_quotes], verbose_name='Кнопка на русском'),
        ),
        migrations.AlterField(
            model_name='step',
            name='button_ukr',
            field=models.CharField(help_text='Максимум 46 символов', max_length=46, validators=[database.models.validate_no_dbl_quotes], verbose_name='Кнопка на украинском'),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(help_text='Лучше начать с кода раздела "xxx_", только английские маленькие буквы и нижнее почеркивание. Чем короче тем лучше :)', max_length=30, verbose_name='Имя шага англ'),
        ),
        migrations.AlterField(
            model_name='step',
            name='text_rus',
            field=models.TextField(help_text='Не используйте "двойные кавычки"!', validators=[database.models.validate_no_dbl_quotes], verbose_name='Текст на русском'),
        ),
        migrations.AlterField(
            model_name='step',
            name='text_ukr',
            field=models.TextField(blank=True, help_text='Не используйте "двойные кавычки"!', null=True, validators=[database.models.validate_no_dbl_quotes], verbose_name='Текст на украинском'),
        ),
    ]
